/*
 * sometitle
 * The REST API for Essbase provides an automation framework for managing Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.appliedolap.essbase.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.appliedolap.essbase.client.model.Link;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LayoutMetadata
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-30T09:44:26.987-07:00[America/Los_Angeles]")
public class LayoutMetadata {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private String user;

  public static final String SERIALIZED_NAME_USER_DEFAULT = "userDefault";
  @SerializedName(SERIALIZED_NAME_USER_DEFAULT)
  private Boolean userDefault;

  public static final String SERIALIZED_NAME_DB_DEFAULT = "dbDefault";
  @SerializedName(SERIALIZED_NAME_DB_DEFAULT)
  private Boolean dbDefault;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private List<Link> links = null;


  public LayoutMetadata name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public LayoutMetadata user(String user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUser() {
    return user;
  }


  public void setUser(String user) {
    this.user = user;
  }


  public LayoutMetadata userDefault(Boolean userDefault) {
    
    this.userDefault = userDefault;
    return this;
  }

   /**
   * Get userDefault
   * @return userDefault
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getUserDefault() {
    return userDefault;
  }


  public void setUserDefault(Boolean userDefault) {
    this.userDefault = userDefault;
  }


  public LayoutMetadata dbDefault(Boolean dbDefault) {
    
    this.dbDefault = dbDefault;
    return this;
  }

   /**
   * Get dbDefault
   * @return dbDefault
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDbDefault() {
    return dbDefault;
  }


  public void setDbDefault(Boolean dbDefault) {
    this.dbDefault = dbDefault;
  }


  public LayoutMetadata links(List<Link> links) {
    
    this.links = links;
    return this;
  }

  public LayoutMetadata addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Link> getLinks() {
    return links;
  }


  public void setLinks(List<Link> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LayoutMetadata layoutMetadata = (LayoutMetadata) o;
    return Objects.equals(this.name, layoutMetadata.name) &&
        Objects.equals(this.user, layoutMetadata.user) &&
        Objects.equals(this.userDefault, layoutMetadata.userDefault) &&
        Objects.equals(this.dbDefault, layoutMetadata.dbDefault) &&
        Objects.equals(this.links, layoutMetadata.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, user, userDefault, dbDefault, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LayoutMetadata {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    userDefault: ").append(toIndentedString(userDefault)).append("\n");
    sb.append("    dbDefault: ").append(toIndentedString(dbDefault)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

