/*
 * sometitle
 * The REST API for Essbase provides an automation framework for managing Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.appliedolap.essbase.client.api;

import com.appliedolap.essbase.client.ApiClient;
import com.appliedolap.essbase.client.ApiException;
import com.appliedolap.essbase.client.ApiResponse;
import com.appliedolap.essbase.client.Pair;

import com.appliedolap.essbase.client.model.FilterBean;
import com.appliedolap.essbase.client.model.FilterCopy;
import com.appliedolap.essbase.client.model.FilterList;
import com.appliedolap.essbase.client.model.FilterRowList;
import com.appliedolap.essbase.client.model.UserGroupProvisionInfo;
import com.appliedolap.essbase.client.model.UserGroupProvisionInfoList;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class FiltersApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public FiltersApi() {
    this(new ApiClient());
  }

  public FiltersApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Add Permissions
   * &lt;p&gt;Adds permissions, in the named filter, for the named user or group.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;User or group details.&lt;/p&gt; (required)
   * @return UserGroupProvisionInfo
   * @throws ApiException if fails to make API call
   */
  public UserGroupProvisionInfo filtersAddFilterPermission(String applicationName, String databaseName, String filterName, UserGroupProvisionInfo body) throws ApiException {
    ApiResponse<UserGroupProvisionInfo> localVarResponse = filtersAddFilterPermissionWithHttpInfo(applicationName, databaseName, filterName, body);
    return localVarResponse.getData();
  }

  /**
   * Add Permissions
   * &lt;p&gt;Adds permissions, in the named filter, for the named user or group.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;User or group details.&lt;/p&gt; (required)
   * @return ApiResponse&lt;UserGroupProvisionInfo&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserGroupProvisionInfo> filtersAddFilterPermissionWithHttpInfo(String applicationName, String databaseName, String filterName, UserGroupProvisionInfo body) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersAddFilterPermissionRequestBuilder(applicationName, databaseName, filterName, body);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersAddFilterPermission", localVarResponse);
        }
        return new ApiResponse<UserGroupProvisionInfo>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<UserGroupProvisionInfo>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersAddFilterPermissionRequestBuilder(String applicationName, String databaseName, String filterName, UserGroupProvisionInfo body) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersAddFilterPermission");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersAddFilterPermission");
    }
    // verify the required parameter 'filterName' is set
    if (filterName == null) {
      throw new ApiException(400, "Missing the required parameter 'filterName' when calling filtersAddFilterPermission");
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling filtersAddFilterPermission");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters/{filterName}/permissions"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()))
        .replace("{filterName}", ApiClient.urlEncode(filterName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Copy Filter
   * &lt;p&gt;Copies a filter in the specified application and database and returns the new filter.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param body Filter copy details (required)
   * @return FilterBean
   * @throws ApiException if fails to make API call
   */
  public FilterBean filtersCopyFilter(String applicationName, String databaseName, FilterCopy body) throws ApiException {
    ApiResponse<FilterBean> localVarResponse = filtersCopyFilterWithHttpInfo(applicationName, databaseName, body);
    return localVarResponse.getData();
  }

  /**
   * Copy Filter
   * &lt;p&gt;Copies a filter in the specified application and database and returns the new filter.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param body Filter copy details (required)
   * @return ApiResponse&lt;FilterBean&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FilterBean> filtersCopyFilterWithHttpInfo(String applicationName, String databaseName, FilterCopy body) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersCopyFilterRequestBuilder(applicationName, databaseName, body);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersCopyFilter", localVarResponse);
        }
        return new ApiResponse<FilterBean>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<FilterBean>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersCopyFilterRequestBuilder(String applicationName, String databaseName, FilterCopy body) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersCopyFilter");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersCopyFilter");
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling filtersCopyFilter");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters/filterops/copy"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create Filter
   * &lt;p&gt;Creates the filter in the specified application and database and returns the created filter&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;Filter details.&lt;/p&gt; (required)
   * @return FilterBean
   * @throws ApiException if fails to make API call
   */
  public FilterBean filtersCreateFilter(String applicationName, String databaseName, FilterBean body) throws ApiException {
    ApiResponse<FilterBean> localVarResponse = filtersCreateFilterWithHttpInfo(applicationName, databaseName, body);
    return localVarResponse.getData();
  }

  /**
   * Create Filter
   * &lt;p&gt;Creates the filter in the specified application and database and returns the created filter&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;Filter details.&lt;/p&gt; (required)
   * @return ApiResponse&lt;FilterBean&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FilterBean> filtersCreateFilterWithHttpInfo(String applicationName, String databaseName, FilterBean body) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersCreateFilterRequestBuilder(applicationName, databaseName, body);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersCreateFilter", localVarResponse);
        }
        return new ApiResponse<FilterBean>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<FilterBean>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersCreateFilterRequestBuilder(String applicationName, String databaseName, FilterBean body) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersCreateFilter");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersCreateFilter");
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling filtersCreateFilter");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete Filter
   * &lt;p&gt;Deletes the named filter in the specified application and database.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @throws ApiException if fails to make API call
   */
  public void filtersDeleteFilter(String applicationName, String databaseName, String filterName) throws ApiException {
    filtersDeleteFilterWithHttpInfo(applicationName, databaseName, filterName);
  }

  /**
   * Delete Filter
   * &lt;p&gt;Deletes the named filter in the specified application and database.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> filtersDeleteFilterWithHttpInfo(String applicationName, String databaseName, String filterName) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersDeleteFilterRequestBuilder(applicationName, databaseName, filterName);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersDeleteFilter", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersDeleteFilterRequestBuilder(String applicationName, String databaseName, String filterName) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersDeleteFilter");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersDeleteFilter");
    }
    // verify the required parameter 'filterName' is set
    if (filterName == null) {
      throw new ApiException(400, "Missing the required parameter 'filterName' when calling filtersDeleteFilter");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters/{filterName}"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()))
        .replace("{filterName}", ApiClient.urlEncode(filterName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update Filter
   * &lt;p&gt;Updates the named filter in the specified application and database, and returns the updated filter.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;Filter details.&lt;/p&gt; (required)
   * @return FilterBean
   * @throws ApiException if fails to make API call
   */
  public FilterBean filtersEditFilter(String applicationName, String databaseName, String filterName, FilterBean body) throws ApiException {
    ApiResponse<FilterBean> localVarResponse = filtersEditFilterWithHttpInfo(applicationName, databaseName, filterName, body);
    return localVarResponse.getData();
  }

  /**
   * Update Filter
   * &lt;p&gt;Updates the named filter in the specified application and database, and returns the updated filter.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;Filter details.&lt;/p&gt; (required)
   * @return ApiResponse&lt;FilterBean&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FilterBean> filtersEditFilterWithHttpInfo(String applicationName, String databaseName, String filterName, FilterBean body) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersEditFilterRequestBuilder(applicationName, databaseName, filterName, body);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersEditFilter", localVarResponse);
        }
        return new ApiResponse<FilterBean>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<FilterBean>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersEditFilterRequestBuilder(String applicationName, String databaseName, String filterName, FilterBean body) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersEditFilter");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersEditFilter");
    }
    // verify the required parameter 'filterName' is set
    if (filterName == null) {
      throw new ApiException(400, "Missing the required parameter 'filterName' when calling filtersEditFilter");
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling filtersEditFilter");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters/{filterName}"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()))
        .replace("{filterName}", ApiClient.urlEncode(filterName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Filter
   * &lt;p&gt;Returns the named filter from the specified application and database.&lt;p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @return FilterBean
   * @throws ApiException if fails to make API call
   */
  public FilterBean filtersGetFilter(String applicationName, String databaseName, String filterName) throws ApiException {
    ApiResponse<FilterBean> localVarResponse = filtersGetFilterWithHttpInfo(applicationName, databaseName, filterName);
    return localVarResponse.getData();
  }

  /**
   * Get Filter
   * &lt;p&gt;Returns the named filter from the specified application and database.&lt;p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @return ApiResponse&lt;FilterBean&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FilterBean> filtersGetFilterWithHttpInfo(String applicationName, String databaseName, String filterName) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersGetFilterRequestBuilder(applicationName, databaseName, filterName);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersGetFilter", localVarResponse);
        }
        return new ApiResponse<FilterBean>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<FilterBean>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersGetFilterRequestBuilder(String applicationName, String databaseName, String filterName) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersGetFilter");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersGetFilter");
    }
    // verify the required parameter 'filterName' is set
    if (filterName == null) {
      throw new ApiException(400, "Missing the required parameter 'filterName' when calling filtersGetFilter");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters/{filterName}"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()))
        .replace("{filterName}", ApiClient.urlEncode(filterName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Permissions
   * &lt;p&gt;Retrieves permissions associated with the named filter.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @return List&lt;UserGroupProvisionInfoList&gt;
   * @throws ApiException if fails to make API call
   */
  public List<UserGroupProvisionInfoList> filtersGetFilterPermissions(String applicationName, String databaseName, String filterName) throws ApiException {
    ApiResponse<List<UserGroupProvisionInfoList>> localVarResponse = filtersGetFilterPermissionsWithHttpInfo(applicationName, databaseName, filterName);
    return localVarResponse.getData();
  }

  /**
   * Get Permissions
   * &lt;p&gt;Retrieves permissions associated with the named filter.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @return ApiResponse&lt;List&lt;UserGroupProvisionInfoList&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<UserGroupProvisionInfoList>> filtersGetFilterPermissionsWithHttpInfo(String applicationName, String databaseName, String filterName) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersGetFilterPermissionsRequestBuilder(applicationName, databaseName, filterName);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersGetFilterPermissions", localVarResponse);
        }
        return new ApiResponse<List<UserGroupProvisionInfoList>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<UserGroupProvisionInfoList>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersGetFilterPermissionsRequestBuilder(String applicationName, String databaseName, String filterName) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersGetFilterPermissions");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersGetFilterPermissions");
    }
    // verify the required parameter 'filterName' is set
    if (filterName == null) {
      throw new ApiException(400, "Missing the required parameter 'filterName' when calling filtersGetFilterPermissions");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters/{filterName}/permissions"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()))
        .replace("{filterName}", ApiClient.urlEncode(filterName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Filter Rows
   * &lt;p&gt;Returns the access definition rows from the specified filter.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @return FilterRowList
   * @throws ApiException if fails to make API call
   */
  public FilterRowList filtersGetFilterRows(String applicationName, String databaseName, String filterName) throws ApiException {
    ApiResponse<FilterRowList> localVarResponse = filtersGetFilterRowsWithHttpInfo(applicationName, databaseName, filterName);
    return localVarResponse.getData();
  }

  /**
   * Get Filter Rows
   * &lt;p&gt;Returns the access definition rows from the specified filter.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @return ApiResponse&lt;FilterRowList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FilterRowList> filtersGetFilterRowsWithHttpInfo(String applicationName, String databaseName, String filterName) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersGetFilterRowsRequestBuilder(applicationName, databaseName, filterName);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersGetFilterRows", localVarResponse);
        }
        return new ApiResponse<FilterRowList>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<FilterRowList>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersGetFilterRowsRequestBuilder(String applicationName, String databaseName, String filterName) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersGetFilterRows");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersGetFilterRows");
    }
    // verify the required parameter 'filterName' is set
    if (filterName == null) {
      throw new ApiException(400, "Missing the required parameter 'filterName' when calling filtersGetFilterRows");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters/{filterName}/rows"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()))
        .replace("{filterName}", ApiClient.urlEncode(filterName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Filters
   * &lt;p&gt;Returns all the filters from the specified application and database.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @return List&lt;FilterList&gt;
   * @throws ApiException if fails to make API call
   */
  public List<FilterList> filtersListFilters(String applicationName, String databaseName) throws ApiException {
    ApiResponse<List<FilterList>> localVarResponse = filtersListFiltersWithHttpInfo(applicationName, databaseName);
    return localVarResponse.getData();
  }

  /**
   * Get Filters
   * &lt;p&gt;Returns all the filters from the specified application and database.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @return ApiResponse&lt;List&lt;FilterList&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<FilterList>> filtersListFiltersWithHttpInfo(String applicationName, String databaseName) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersListFiltersRequestBuilder(applicationName, databaseName);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersListFilters", localVarResponse);
        }
        return new ApiResponse<List<FilterList>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<FilterList>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersListFiltersRequestBuilder(String applicationName, String databaseName) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersListFilters");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersListFilters");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete Permission
   * &lt;p&gt;Removes permissions from a filter for the specified user or group.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @param userGroupId &lt;p&gt;User or group ID.&lt;/p&gt; (required)
   * @param group &lt;p&gt;True if the userGroupId refers to a group; false if it refers to a user.&lt;/p&gt; (required)
   * @throws ApiException if fails to make API call
   */
  public void filtersRemoveFilterPermission(String applicationName, String databaseName, String filterName, String userGroupId, Boolean group) throws ApiException {
    filtersRemoveFilterPermissionWithHttpInfo(applicationName, databaseName, filterName, userGroupId, group);
  }

  /**
   * Delete Permission
   * &lt;p&gt;Removes permissions from a filter for the specified user or group.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @param userGroupId &lt;p&gt;User or group ID.&lt;/p&gt; (required)
   * @param group &lt;p&gt;True if the userGroupId refers to a group; false if it refers to a user.&lt;/p&gt; (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> filtersRemoveFilterPermissionWithHttpInfo(String applicationName, String databaseName, String filterName, String userGroupId, Boolean group) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersRemoveFilterPermissionRequestBuilder(applicationName, databaseName, filterName, userGroupId, group);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersRemoveFilterPermission", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersRemoveFilterPermissionRequestBuilder(String applicationName, String databaseName, String filterName, String userGroupId, Boolean group) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersRemoveFilterPermission");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersRemoveFilterPermission");
    }
    // verify the required parameter 'filterName' is set
    if (filterName == null) {
      throw new ApiException(400, "Missing the required parameter 'filterName' when calling filtersRemoveFilterPermission");
    }
    // verify the required parameter 'userGroupId' is set
    if (userGroupId == null) {
      throw new ApiException(400, "Missing the required parameter 'userGroupId' when calling filtersRemoveFilterPermission");
    }
    // verify the required parameter 'group' is set
    if (group == null) {
      throw new ApiException(400, "Missing the required parameter 'group' when calling filtersRemoveFilterPermission");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters/{filterName}/permissions/{userGroupId}"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()))
        .replace("{filterName}", ApiClient.urlEncode(filterName.toString()))
        .replace("{userGroupId}", ApiClient.urlEncode(userGroupId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "group";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("group", group));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Rename Filter
   * Renames the filter in the specified application and database and returns the created filter
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;Filter rename details.&lt;/p&gt; (required)
   * @return FilterBean
   * @throws ApiException if fails to make API call
   */
  public FilterBean filtersRenameFilter(String applicationName, String databaseName, FilterCopy body) throws ApiException {
    ApiResponse<FilterBean> localVarResponse = filtersRenameFilterWithHttpInfo(applicationName, databaseName, body);
    return localVarResponse.getData();
  }

  /**
   * Rename Filter
   * Renames the filter in the specified application and database and returns the created filter
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;Filter rename details.&lt;/p&gt; (required)
   * @return ApiResponse&lt;FilterBean&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FilterBean> filtersRenameFilterWithHttpInfo(String applicationName, String databaseName, FilterCopy body) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersRenameFilterRequestBuilder(applicationName, databaseName, body);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersRenameFilter", localVarResponse);
        }
        return new ApiResponse<FilterBean>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<FilterBean>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersRenameFilterRequestBuilder(String applicationName, String databaseName, FilterCopy body) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersRenameFilter");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersRenameFilter");
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling filtersRenameFilter");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters/filterops/rename"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Edit Permissions
   * &lt;p&gt;Replaces all the users and groups assigned to the filter with a new list of users and groups.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;User or group details.&lt;/p&gt; (required)
   * @return UserGroupProvisionInfo
   * @throws ApiException if fails to make API call
   */
  public UserGroupProvisionInfo filtersReplaceFilterPermission(String applicationName, String databaseName, String filterName, UserGroupProvisionInfoList body) throws ApiException {
    ApiResponse<UserGroupProvisionInfo> localVarResponse = filtersReplaceFilterPermissionWithHttpInfo(applicationName, databaseName, filterName, body);
    return localVarResponse.getData();
  }

  /**
   * Edit Permissions
   * &lt;p&gt;Replaces all the users and groups assigned to the filter with a new list of users and groups.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param filterName &lt;p&gt;Filter name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;User or group details.&lt;/p&gt; (required)
   * @return ApiResponse&lt;UserGroupProvisionInfo&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserGroupProvisionInfo> filtersReplaceFilterPermissionWithHttpInfo(String applicationName, String databaseName, String filterName, UserGroupProvisionInfoList body) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersReplaceFilterPermissionRequestBuilder(applicationName, databaseName, filterName, body);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersReplaceFilterPermission", localVarResponse);
        }
        return new ApiResponse<UserGroupProvisionInfo>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<UserGroupProvisionInfo>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersReplaceFilterPermissionRequestBuilder(String applicationName, String databaseName, String filterName, UserGroupProvisionInfoList body) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersReplaceFilterPermission");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersReplaceFilterPermission");
    }
    // verify the required parameter 'filterName' is set
    if (filterName == null) {
      throw new ApiException(400, "Missing the required parameter 'filterName' when calling filtersReplaceFilterPermission");
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling filtersReplaceFilterPermission");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters/{filterName}/permissions"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()))
        .replace("{filterName}", ApiClient.urlEncode(filterName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Validate Filter
   * &lt;p&gt;Validates the filter in the specified application and database.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;Filter details.&lt;/p&gt; (required)
   * @throws ApiException if fails to make API call
   */
  public void filtersValidateFilter(String applicationName, String databaseName, FilterBean body) throws ApiException {
    filtersValidateFilterWithHttpInfo(applicationName, databaseName, body);
  }

  /**
   * Validate Filter
   * &lt;p&gt;Validates the filter in the specified application and database.&lt;/p&gt;
   * @param applicationName &lt;p&gt;Application name.&lt;/p&gt; (required)
   * @param databaseName &lt;p&gt;Database name.&lt;/p&gt; (required)
   * @param body &lt;p&gt;Filter details.&lt;/p&gt; (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> filtersValidateFilterWithHttpInfo(String applicationName, String databaseName, FilterBean body) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = filtersValidateFilterRequestBuilder(applicationName, databaseName, body);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("filtersValidateFilter", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder filtersValidateFilterRequestBuilder(String applicationName, String databaseName, FilterBean body) throws ApiException {
    // verify the required parameter 'applicationName' is set
    if (applicationName == null) {
      throw new ApiException(400, "Missing the required parameter 'applicationName' when calling filtersValidateFilter");
    }
    // verify the required parameter 'databaseName' is set
    if (databaseName == null) {
      throw new ApiException(400, "Missing the required parameter 'databaseName' when calling filtersValidateFilter");
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling filtersValidateFilter");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/applications/{applicationName}/databases/{databaseName}/filters/filterops/validate"
        .replace("{applicationName}", ApiClient.urlEncode(applicationName.toString()))
        .replace("{databaseName}", ApiClient.urlEncode(databaseName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
