/*
 * sometitle
 * The REST API for Essbase provides an automation framework for managing Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.appliedolap.essbase.client.api;

import com.appliedolap.essbase.client.ApiClient;
import com.appliedolap.essbase.client.ApiException;
import com.appliedolap.essbase.client.ApiResponse;
import com.appliedolap.essbase.client.Pair;

import com.appliedolap.essbase.client.model.DatabaseSettings;
import com.appliedolap.essbase.client.model.Limits;
import com.appliedolap.essbase.client.model.Settings;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class PlatformServiceSettingsApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public PlatformServiceSettingsApi() {
    this(new ApiClient());
  }

  public PlatformServiceSettingsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Get Available PSM Settings
   * Returns the platform service settings. This API returns the links to various settings available in this release.
   * @return Settings
   * @throws ApiException if fails to make API call
   */
  public Settings pSMSettingsGetAll() throws ApiException {
    ApiResponse<Settings> localVarResponse = pSMSettingsGetAllWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * Get Available PSM Settings
   * Returns the platform service settings. This API returns the links to various settings available in this release.
   * @return ApiResponse&lt;Settings&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Settings> pSMSettingsGetAllWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = pSMSettingsGetAllRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("pSMSettingsGetAll", localVarResponse);
        }
        return new ApiResponse<Settings>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Settings>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder pSMSettingsGetAllRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/settings";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Database Settings
   * Get the platform service database settings.
   * @return Limits
   * @throws ApiException if fails to make API call
   */
  public Limits pSMSettingsGetDatabaseSettings() throws ApiException {
    ApiResponse<Limits> localVarResponse = pSMSettingsGetDatabaseSettingsWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * Get Database Settings
   * Get the platform service database settings.
   * @return ApiResponse&lt;Limits&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Limits> pSMSettingsGetDatabaseSettingsWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = pSMSettingsGetDatabaseSettingsRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("pSMSettingsGetDatabaseSettings", localVarResponse);
        }
        return new ApiResponse<Limits>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Limits>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder pSMSettingsGetDatabaseSettingsRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/settings/database";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Resource Settings
   * Returns the platform service resource settings.
   * @return Limits
   * @throws ApiException if fails to make API call
   */
  public Limits pSMSettingsGetResources() throws ApiException {
    ApiResponse<Limits> localVarResponse = pSMSettingsGetResourcesWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * Get Resource Settings
   * Returns the platform service resource settings.
   * @return ApiResponse&lt;Limits&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Limits> pSMSettingsGetResourcesWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = pSMSettingsGetResourcesRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("pSMSettingsGetResources", localVarResponse);
        }
        return new ApiResponse<Limits>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Limits>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder pSMSettingsGetResourcesRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/settings/resources";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Maintenance Settings
   * Get the platform service maintenance settings, such as disk space and memory.
   * @return Limits
   * @throws ApiException if fails to make API call
   */
  public Limits pSMSettingsGetSystemMaintenanceLimits() throws ApiException {
    ApiResponse<Limits> localVarResponse = pSMSettingsGetSystemMaintenanceLimitsWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * Get Maintenance Settings
   * Get the platform service maintenance settings, such as disk space and memory.
   * @return ApiResponse&lt;Limits&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Limits> pSMSettingsGetSystemMaintenanceLimitsWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = pSMSettingsGetSystemMaintenanceLimitsRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("pSMSettingsGetSystemMaintenanceLimits", localVarResponse);
        }
        return new ApiResponse<Limits>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Limits>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder pSMSettingsGetSystemMaintenanceLimitsRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/settings/maintenance";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Store Database Settings
   * Save the platform service database settings.
   * @param body  (optional)
   * @return Limits
   * @throws ApiException if fails to make API call
   */
  public Limits pSMSettingsSetDatabaseSettings(DatabaseSettings body) throws ApiException {
    ApiResponse<Limits> localVarResponse = pSMSettingsSetDatabaseSettingsWithHttpInfo(body);
    return localVarResponse.getData();
  }

  /**
   * Store Database Settings
   * Save the platform service database settings.
   * @param body  (optional)
   * @return ApiResponse&lt;Limits&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Limits> pSMSettingsSetDatabaseSettingsWithHttpInfo(DatabaseSettings body) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = pSMSettingsSetDatabaseSettingsRequestBuilder(body);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("pSMSettingsSetDatabaseSettings", localVarResponse);
        }
        return new ApiResponse<Limits>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Limits>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder pSMSettingsSetDatabaseSettingsRequestBuilder(DatabaseSettings body) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/settings/database";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Store Resource Settings
   * Save the platform service resource settings.
   * @param body  (optional)
   * @return Limits
   * @throws ApiException if fails to make API call
   */
  public Limits pSMSettingsSetResources(Limits body) throws ApiException {
    ApiResponse<Limits> localVarResponse = pSMSettingsSetResourcesWithHttpInfo(body);
    return localVarResponse.getData();
  }

  /**
   * Store Resource Settings
   * Save the platform service resource settings.
   * @param body  (optional)
   * @return ApiResponse&lt;Limits&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Limits> pSMSettingsSetResourcesWithHttpInfo(Limits body) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = pSMSettingsSetResourcesRequestBuilder(body);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("pSMSettingsSetResources", localVarResponse);
        }
        return new ApiResponse<Limits>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Limits>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder pSMSettingsSetResourcesRequestBuilder(Limits body) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/settings/resources";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
