/*
 * Essbase REST API
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.appliedolap.essbase.client.api;

import com.appliedolap.essbase.client.ApiClient;
import com.appliedolap.essbase.client.ApiException;
import com.appliedolap.essbase.client.ApiResponse;
import com.appliedolap.essbase.client.Pair;

import com.appliedolap.essbase.client.model.Variable;
import com.appliedolap.essbase.client.model.VariableList;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ServerVariablesApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public ServerVariablesApi() {
    this(new ApiClient());
  }

  public ServerVariablesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create Server Variable
   * &lt;p&gt;Creates a server substitution variable and returns details about it.&lt;/p&gt;
   * @param variable &lt;p&gt;Variable details.&lt;/p&gt; (required)
   * @return Variable
   * @throws ApiException if fails to make API call
   */
  public Variable variablesCreateServerVariable(Variable variable) throws ApiException {
    ApiResponse<Variable> localVarResponse = variablesCreateServerVariableWithHttpInfo(variable);
    return localVarResponse.getData();
  }

  /**
   * Create Server Variable
   * &lt;p&gt;Creates a server substitution variable and returns details about it.&lt;/p&gt;
   * @param variable &lt;p&gt;Variable details.&lt;/p&gt; (required)
   * @return ApiResponse&lt;Variable&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Variable> variablesCreateServerVariableWithHttpInfo(Variable variable) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = variablesCreateServerVariableRequestBuilder(variable);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("variablesCreateServerVariable", localVarResponse);
        }
        return new ApiResponse<Variable>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Variable>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder variablesCreateServerVariableRequestBuilder(Variable variable) throws ApiException {
    // verify the required parameter 'variable' is set
    if (variable == null) {
      throw new ApiException(400, "Missing the required parameter 'variable' when calling variablesCreateServerVariable");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/variables";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(variable);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete Server Variable
   * &lt;p&gt;Deletes the given substitution variable from the server.&lt;/p&gt;
   * @param variableName &lt;p&gt;Variable name.&lt;/p&gt; (required)
   * @throws ApiException if fails to make API call
   */
  public void variablesDeleteServerVariable(String variableName) throws ApiException {
    variablesDeleteServerVariableWithHttpInfo(variableName);
  }

  /**
   * Delete Server Variable
   * &lt;p&gt;Deletes the given substitution variable from the server.&lt;/p&gt;
   * @param variableName &lt;p&gt;Variable name.&lt;/p&gt; (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> variablesDeleteServerVariableWithHttpInfo(String variableName) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = variablesDeleteServerVariableRequestBuilder(variableName);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("variablesDeleteServerVariable", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder variablesDeleteServerVariableRequestBuilder(String variableName) throws ApiException {
    // verify the required parameter 'variableName' is set
    if (variableName == null) {
      throw new ApiException(400, "Missing the required parameter 'variableName' when calling variablesDeleteServerVariable");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/variables/{variableName}"
        .replace("{variableName}", ApiClient.urlEncode(variableName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update Server Variable
   * &lt;p&gt;Updates a substitution variable on the server, and returns the updated variable.&lt;/p&gt;
   * @param variableName &lt;p&gt;Variable name.&lt;/p&gt; (required)
   * @param variable &lt;p&gt;Variable details.&lt;/p&gt; (required)
   * @return Variable
   * @throws ApiException if fails to make API call
   */
  public Variable variablesEditServerVariable(String variableName, Variable variable) throws ApiException {
    ApiResponse<Variable> localVarResponse = variablesEditServerVariableWithHttpInfo(variableName, variable);
    return localVarResponse.getData();
  }

  /**
   * Update Server Variable
   * &lt;p&gt;Updates a substitution variable on the server, and returns the updated variable.&lt;/p&gt;
   * @param variableName &lt;p&gt;Variable name.&lt;/p&gt; (required)
   * @param variable &lt;p&gt;Variable details.&lt;/p&gt; (required)
   * @return ApiResponse&lt;Variable&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Variable> variablesEditServerVariableWithHttpInfo(String variableName, Variable variable) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = variablesEditServerVariableRequestBuilder(variableName, variable);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("variablesEditServerVariable", localVarResponse);
        }
        return new ApiResponse<Variable>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Variable>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder variablesEditServerVariableRequestBuilder(String variableName, Variable variable) throws ApiException {
    // verify the required parameter 'variableName' is set
    if (variableName == null) {
      throw new ApiException(400, "Missing the required parameter 'variableName' when calling variablesEditServerVariable");
    }
    // verify the required parameter 'variable' is set
    if (variable == null) {
      throw new ApiException(400, "Missing the required parameter 'variable' when calling variablesEditServerVariable");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/variables/{variableName}"
        .replace("{variableName}", ApiClient.urlEncode(variableName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(variable);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Server Variable
   * &lt;p&gt;Returns substitution variable details from the server.&lt;/p&gt;
   * @param variableName &lt;p&gt;Variable name.&lt;/p&gt; (required)
   * @return Variable
   * @throws ApiException if fails to make API call
   */
  public Variable variablesGetServerVariable(String variableName) throws ApiException {
    ApiResponse<Variable> localVarResponse = variablesGetServerVariableWithHttpInfo(variableName);
    return localVarResponse.getData();
  }

  /**
   * Get Server Variable
   * &lt;p&gt;Returns substitution variable details from the server.&lt;/p&gt;
   * @param variableName &lt;p&gt;Variable name.&lt;/p&gt; (required)
   * @return ApiResponse&lt;Variable&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Variable> variablesGetServerVariableWithHttpInfo(String variableName) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = variablesGetServerVariableRequestBuilder(variableName);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("variablesGetServerVariable", localVarResponse);
        }
        return new ApiResponse<Variable>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Variable>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder variablesGetServerVariableRequestBuilder(String variableName) throws ApiException {
    // verify the required parameter 'variableName' is set
    if (variableName == null) {
      throw new ApiException(400, "Missing the required parameter 'variableName' when calling variablesGetServerVariable");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/variables/{variableName}"
        .replace("{variableName}", ApiClient.urlEncode(variableName.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Server Variables
   * &lt;p&gt;Returns all the substitution variables from the Essbase server.&lt;/p&gt;
   * @param orderBy Order By specification in format:&lt;code&gt;column&lt;/code&gt;:&lt;code&gt;direction&lt;/code&gt;. e.g.&lt;code&gt;name:asc&lt;/code&gt; &lt;/p&gt; (optional, default to )
   * @param all  (optional, default to false)
   * @return VariableList
   * @throws ApiException if fails to make API call
   */
  public VariableList variablesListServerVariables(String orderBy, String all) throws ApiException {
    ApiResponse<VariableList> localVarResponse = variablesListServerVariablesWithHttpInfo(orderBy, all);
    return localVarResponse.getData();
  }

  /**
   * Get Server Variables
   * &lt;p&gt;Returns all the substitution variables from the Essbase server.&lt;/p&gt;
   * @param orderBy Order By specification in format:&lt;code&gt;column&lt;/code&gt;:&lt;code&gt;direction&lt;/code&gt;. e.g.&lt;code&gt;name:asc&lt;/code&gt; &lt;/p&gt; (optional, default to )
   * @param all  (optional, default to false)
   * @return ApiResponse&lt;VariableList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<VariableList> variablesListServerVariablesWithHttpInfo(String orderBy, String all) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = variablesListServerVariablesRequestBuilder(orderBy, all);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("variablesListServerVariables", localVarResponse);
        }
        return new ApiResponse<VariableList>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<VariableList>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder variablesListServerVariablesRequestBuilder(String orderBy, String all) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/variables";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "orderBy";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("orderBy", orderBy));
    localVarQueryParameterBaseName = "all";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("all", all));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json, application/xml");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
