/*
 * sometitle
 * The REST API for Essbase provides an automation framework for managing Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.appliedolap.essbase.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.appliedolap.essbase.client.ApiClient;
/**
 * BufferSettings
 */
@JsonPropertyOrder({
  BufferSettings.JSON_PROPERTY_DATA_RETRIEVAL_BUFFER_SIZE,
  BufferSettings.JSON_PROPERTY_DATA_RETRIEVAL_SORT_BUFFER_SIZE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class BufferSettings {
  public static final String JSON_PROPERTY_DATA_RETRIEVAL_BUFFER_SIZE = "dataRetrievalBufferSize";
  @jakarta.annotation.Nullable
  private Long dataRetrievalBufferSize;

  public static final String JSON_PROPERTY_DATA_RETRIEVAL_SORT_BUFFER_SIZE = "dataRetrievalSortBufferSize";
  @jakarta.annotation.Nullable
  private Long dataRetrievalSortBufferSize;

  public BufferSettings() { 
  }

  public BufferSettings dataRetrievalBufferSize(@jakarta.annotation.Nullable Long dataRetrievalBufferSize) {
    this.dataRetrievalBufferSize = dataRetrievalBufferSize;
    return this;
  }

  /**
   * Get dataRetrievalBufferSize
   * @return dataRetrievalBufferSize
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_RETRIEVAL_BUFFER_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getDataRetrievalBufferSize() {
    return dataRetrievalBufferSize;
  }


  @JsonProperty(JSON_PROPERTY_DATA_RETRIEVAL_BUFFER_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataRetrievalBufferSize(@jakarta.annotation.Nullable Long dataRetrievalBufferSize) {
    this.dataRetrievalBufferSize = dataRetrievalBufferSize;
  }


  public BufferSettings dataRetrievalSortBufferSize(@jakarta.annotation.Nullable Long dataRetrievalSortBufferSize) {
    this.dataRetrievalSortBufferSize = dataRetrievalSortBufferSize;
    return this;
  }

  /**
   * Get dataRetrievalSortBufferSize
   * @return dataRetrievalSortBufferSize
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_RETRIEVAL_SORT_BUFFER_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getDataRetrievalSortBufferSize() {
    return dataRetrievalSortBufferSize;
  }


  @JsonProperty(JSON_PROPERTY_DATA_RETRIEVAL_SORT_BUFFER_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataRetrievalSortBufferSize(@jakarta.annotation.Nullable Long dataRetrievalSortBufferSize) {
    this.dataRetrievalSortBufferSize = dataRetrievalSortBufferSize;
  }


  /**
   * Return true if this BufferSettings object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BufferSettings bufferSettings = (BufferSettings) o;
    return Objects.equals(this.dataRetrievalBufferSize, bufferSettings.dataRetrievalBufferSize) &&
        Objects.equals(this.dataRetrievalSortBufferSize, bufferSettings.dataRetrievalSortBufferSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataRetrievalBufferSize, dataRetrievalSortBufferSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BufferSettings {\n");
    sb.append("    dataRetrievalBufferSize: ").append(toIndentedString(dataRetrievalBufferSize)).append("\n");
    sb.append("    dataRetrievalSortBufferSize: ").append(toIndentedString(dataRetrievalSortBufferSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `dataRetrievalBufferSize` to the URL query string
    if (getDataRetrievalBufferSize() != null) {
      joiner.add(String.format("%sdataRetrievalBufferSize%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDataRetrievalBufferSize()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `dataRetrievalSortBufferSize` to the URL query string
    if (getDataRetrievalSortBufferSize() != null) {
      joiner.add(String.format("%sdataRetrievalSortBufferSize%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDataRetrievalSortBufferSize()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

