/*
 * Essbase REST API
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.appliedolap.essbase.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.appliedolap.essbase.client.model.FileProperties;
import com.appliedolap.essbase.client.model.SQLProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.appliedolap.essbase.client.ApiClient;
/**
 * DataSourceDefinition
 */
@JsonPropertyOrder({
  DataSourceDefinition.JSON_PROPERTY_HEADER,
  DataSourceDefinition.JSON_PROPERTY_NAME,
  DataSourceDefinition.JSON_PROPERTY_TOKENS,
  DataSourceDefinition.JSON_PROPERTY_TOKENS_COMBINE_OPTION,
  DataSourceDefinition.JSON_PROPERTY_SQL_PROPERTIES,
  DataSourceDefinition.JSON_PROPERTY_FILE_PROPERTIES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class DataSourceDefinition {
  public static final String JSON_PROPERTY_HEADER = "header";
  @jakarta.annotation.Nullable
  private String header;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_TOKENS = "tokens";
  @jakarta.annotation.Nullable
  private List<String> tokens = new ArrayList<>();

  /**
   * Gets or Sets tokensCombineOption
   */
  public enum TokensCombineOptionEnum {
    AND(String.valueOf("AND")),
    
    OR(String.valueOf("OR"));

    private String value;

    TokensCombineOptionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TokensCombineOptionEnum fromValue(String value) {
      for (TokensCombineOptionEnum b : TokensCombineOptionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TOKENS_COMBINE_OPTION = "tokensCombineOption";
  @jakarta.annotation.Nullable
  private TokensCombineOptionEnum tokensCombineOption;

  public static final String JSON_PROPERTY_SQL_PROPERTIES = "sqlProperties";
  @jakarta.annotation.Nullable
  private SQLProperties sqlProperties;

  public static final String JSON_PROPERTY_FILE_PROPERTIES = "fileProperties";
  @jakarta.annotation.Nullable
  private FileProperties fileProperties;

  public DataSourceDefinition() { 
  }

  public DataSourceDefinition header(@jakarta.annotation.Nullable String header) {
    this.header = header;
    return this;
  }

  /**
   * Get header
   * @return header
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEADER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHeader() {
    return header;
  }


  @JsonProperty(JSON_PROPERTY_HEADER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeader(@jakarta.annotation.Nullable String header) {
    this.header = header;
  }


  public DataSourceDefinition name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public DataSourceDefinition tokens(@jakarta.annotation.Nullable List<String> tokens) {
    this.tokens = tokens;
    return this;
  }

  public DataSourceDefinition addTokensItem(String tokensItem) {
    if (this.tokens == null) {
      this.tokens = new ArrayList<>();
    }
    this.tokens.add(tokensItem);
    return this;
  }

  /**
   * Get tokens
   * @return tokens
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getTokens() {
    return tokens;
  }


  @JsonProperty(JSON_PROPERTY_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokens(@jakarta.annotation.Nullable List<String> tokens) {
    this.tokens = tokens;
  }


  public DataSourceDefinition tokensCombineOption(@jakarta.annotation.Nullable TokensCombineOptionEnum tokensCombineOption) {
    this.tokensCombineOption = tokensCombineOption;
    return this;
  }

  /**
   * Get tokensCombineOption
   * @return tokensCombineOption
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKENS_COMBINE_OPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TokensCombineOptionEnum getTokensCombineOption() {
    return tokensCombineOption;
  }


  @JsonProperty(JSON_PROPERTY_TOKENS_COMBINE_OPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokensCombineOption(@jakarta.annotation.Nullable TokensCombineOptionEnum tokensCombineOption) {
    this.tokensCombineOption = tokensCombineOption;
  }


  public DataSourceDefinition sqlProperties(@jakarta.annotation.Nullable SQLProperties sqlProperties) {
    this.sqlProperties = sqlProperties;
    return this;
  }

  /**
   * Get sqlProperties
   * @return sqlProperties
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SQL_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SQLProperties getSqlProperties() {
    return sqlProperties;
  }


  @JsonProperty(JSON_PROPERTY_SQL_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSqlProperties(@jakarta.annotation.Nullable SQLProperties sqlProperties) {
    this.sqlProperties = sqlProperties;
  }


  public DataSourceDefinition fileProperties(@jakarta.annotation.Nullable FileProperties fileProperties) {
    this.fileProperties = fileProperties;
    return this;
  }

  /**
   * Get fileProperties
   * @return fileProperties
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FileProperties getFileProperties() {
    return fileProperties;
  }


  @JsonProperty(JSON_PROPERTY_FILE_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileProperties(@jakarta.annotation.Nullable FileProperties fileProperties) {
    this.fileProperties = fileProperties;
  }


  /**
   * Return true if this DataSourceDefinition object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataSourceDefinition dataSourceDefinition = (DataSourceDefinition) o;
    return Objects.equals(this.header, dataSourceDefinition.header) &&
        Objects.equals(this.name, dataSourceDefinition.name) &&
        Objects.equals(this.tokens, dataSourceDefinition.tokens) &&
        Objects.equals(this.tokensCombineOption, dataSourceDefinition.tokensCombineOption) &&
        Objects.equals(this.sqlProperties, dataSourceDefinition.sqlProperties) &&
        Objects.equals(this.fileProperties, dataSourceDefinition.fileProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, name, tokens, tokensCombineOption, sqlProperties, fileProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataSourceDefinition {\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    tokensCombineOption: ").append(toIndentedString(tokensCombineOption)).append("\n");
    sb.append("    sqlProperties: ").append(toIndentedString(sqlProperties)).append("\n");
    sb.append("    fileProperties: ").append(toIndentedString(fileProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `header` to the URL query string
    if (getHeader() != null) {
      joiner.add(String.format("%sheader%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getHeader()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `tokens` to the URL query string
    if (getTokens() != null) {
      for (int i = 0; i < getTokens().size(); i++) {
        joiner.add(String.format("%stokens%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(ApiClient.valueToString(getTokens().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `tokensCombineOption` to the URL query string
    if (getTokensCombineOption() != null) {
      joiner.add(String.format("%stokensCombineOption%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTokensCombineOption()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `sqlProperties` to the URL query string
    if (getSqlProperties() != null) {
      joiner.add(getSqlProperties().toUrlQueryString(prefix + "sqlProperties" + suffix));
    }

    // add `fileProperties` to the URL query string
    if (getFileProperties() != null) {
      joiner.add(getFileProperties().toUrlQueryString(prefix + "fileProperties" + suffix));
    }

    return joiner.toString();
  }
}

