/*
 * sometitle
 * The REST API for Essbase provides an automation framework for managing Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.appliedolap.essbase.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.appliedolap.essbase.client.model.GridDimension;
import com.appliedolap.essbase.client.model.Slice;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.appliedolap.essbase.client.ApiClient;
/**
 * Grid
 */
@JsonPropertyOrder({
  Grid.JSON_PROPERTY_DIMENSIONS,
  Grid.JSON_PROPERTY_ALIAS,
  Grid.JSON_PROPERTY_SLICE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class Grid {
  public static final String JSON_PROPERTY_DIMENSIONS = "dimensions";
  @jakarta.annotation.Nullable
  private List<GridDimension> dimensions = new ArrayList<>();

  public static final String JSON_PROPERTY_ALIAS = "alias";
  @jakarta.annotation.Nullable
  private String alias;

  public static final String JSON_PROPERTY_SLICE = "slice";
  @jakarta.annotation.Nullable
  private Slice slice;

  public Grid() { 
  }

  public Grid dimensions(@jakarta.annotation.Nullable List<GridDimension> dimensions) {
    this.dimensions = dimensions;
    return this;
  }

  public Grid addDimensionsItem(GridDimension dimensionsItem) {
    if (this.dimensions == null) {
      this.dimensions = new ArrayList<>();
    }
    this.dimensions.add(dimensionsItem);
    return this;
  }

  /**
   * Get dimensions
   * @return dimensions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIMENSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<GridDimension> getDimensions() {
    return dimensions;
  }


  @JsonProperty(JSON_PROPERTY_DIMENSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDimensions(@jakarta.annotation.Nullable List<GridDimension> dimensions) {
    this.dimensions = dimensions;
  }


  public Grid alias(@jakarta.annotation.Nullable String alias) {
    this.alias = alias;
    return this;
  }

  /**
   * Get alias
   * @return alias
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAlias() {
    return alias;
  }


  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlias(@jakarta.annotation.Nullable String alias) {
    this.alias = alias;
  }


  public Grid slice(@jakarta.annotation.Nullable Slice slice) {
    this.slice = slice;
    return this;
  }

  /**
   * Get slice
   * @return slice
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SLICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Slice getSlice() {
    return slice;
  }


  @JsonProperty(JSON_PROPERTY_SLICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSlice(@jakarta.annotation.Nullable Slice slice) {
    this.slice = slice;
  }


  /**
   * Return true if this Grid object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Grid grid = (Grid) o;
    return Objects.equals(this.dimensions, grid.dimensions) &&
        Objects.equals(this.alias, grid.alias) &&
        Objects.equals(this.slice, grid.slice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimensions, alias, slice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Grid {\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    slice: ").append(toIndentedString(slice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `dimensions` to the URL query string
    if (getDimensions() != null) {
      for (int i = 0; i < getDimensions().size(); i++) {
        if (getDimensions().get(i) != null) {
          joiner.add(getDimensions().get(i).toUrlQueryString(String.format("%sdimensions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `alias` to the URL query string
    if (getAlias() != null) {
      joiner.add(String.format("%salias%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAlias()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `slice` to the URL query string
    if (getSlice() != null) {
      joiner.add(getSlice().toUrlQueryString(prefix + "slice" + suffix));
    }

    return joiner.toString();
  }
}

