/*
 * sometitle
 * The REST API for Essbase provides an automation framework for managing Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.appliedolap.essbase.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.appliedolap.essbase.client.ApiClient;
/**
 * GridDimension
 */
@JsonPropertyOrder({
  GridDimension.JSON_PROPERTY_COLUMN,
  GridDimension.JSON_PROPERTY_ROW,
  GridDimension.JSON_PROPERTY_POV,
  GridDimension.JSON_PROPERTY_EXPANDED,
  GridDimension.JSON_PROPERTY_DISPLAY_NAME,
  GridDimension.JSON_PROPERTY_HIDDEN,
  GridDimension.JSON_PROPERTY_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class GridDimension {
  public static final String JSON_PROPERTY_COLUMN = "column";
  @jakarta.annotation.Nullable
  private Integer column;

  public static final String JSON_PROPERTY_ROW = "row";
  @jakarta.annotation.Nullable
  private Integer row;

  public static final String JSON_PROPERTY_POV = "pov";
  @jakarta.annotation.Nullable
  private String pov;

  public static final String JSON_PROPERTY_EXPANDED = "expanded";
  @jakarta.annotation.Nullable
  private Boolean expanded;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @jakarta.annotation.Nullable
  private String displayName;

  public static final String JSON_PROPERTY_HIDDEN = "hidden";
  @jakarta.annotation.Nullable
  private Boolean hidden;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public GridDimension() { 
  }

  public GridDimension column(@jakarta.annotation.Nullable Integer column) {
    this.column = column;
    return this;
  }

  /**
   * Get column
   * @return column
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getColumn() {
    return column;
  }


  @JsonProperty(JSON_PROPERTY_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColumn(@jakarta.annotation.Nullable Integer column) {
    this.column = column;
  }


  public GridDimension row(@jakarta.annotation.Nullable Integer row) {
    this.row = row;
    return this;
  }

  /**
   * Get row
   * @return row
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getRow() {
    return row;
  }


  @JsonProperty(JSON_PROPERTY_ROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRow(@jakarta.annotation.Nullable Integer row) {
    this.row = row;
  }


  public GridDimension pov(@jakarta.annotation.Nullable String pov) {
    this.pov = pov;
    return this;
  }

  /**
   * Get pov
   * @return pov
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPov() {
    return pov;
  }


  @JsonProperty(JSON_PROPERTY_POV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPov(@jakarta.annotation.Nullable String pov) {
    this.pov = pov;
  }


  public GridDimension expanded(@jakarta.annotation.Nullable Boolean expanded) {
    this.expanded = expanded;
    return this;
  }

  /**
   * Get expanded
   * @return expanded
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPANDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getExpanded() {
    return expanded;
  }


  @JsonProperty(JSON_PROPERTY_EXPANDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpanded(@jakarta.annotation.Nullable Boolean expanded) {
    this.expanded = expanded;
  }


  public GridDimension displayName(@jakarta.annotation.Nullable String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(@jakarta.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }


  public GridDimension hidden(@jakarta.annotation.Nullable Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

  /**
   * Get hidden
   * @return hidden
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HIDDEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getHidden() {
    return hidden;
  }


  @JsonProperty(JSON_PROPERTY_HIDDEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHidden(@jakarta.annotation.Nullable Boolean hidden) {
    this.hidden = hidden;
  }


  public GridDimension name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  /**
   * Return true if this GridDimension object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GridDimension gridDimension = (GridDimension) o;
    return Objects.equals(this.column, gridDimension.column) &&
        Objects.equals(this.row, gridDimension.row) &&
        Objects.equals(this.pov, gridDimension.pov) &&
        Objects.equals(this.expanded, gridDimension.expanded) &&
        Objects.equals(this.displayName, gridDimension.displayName) &&
        Objects.equals(this.hidden, gridDimension.hidden) &&
        Objects.equals(this.name, gridDimension.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(column, row, pov, expanded, displayName, hidden, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GridDimension {\n");
    sb.append("    column: ").append(toIndentedString(column)).append("\n");
    sb.append("    row: ").append(toIndentedString(row)).append("\n");
    sb.append("    pov: ").append(toIndentedString(pov)).append("\n");
    sb.append("    expanded: ").append(toIndentedString(expanded)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `column` to the URL query string
    if (getColumn() != null) {
      joiner.add(String.format("%scolumn%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getColumn()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `row` to the URL query string
    if (getRow() != null) {
      joiner.add(String.format("%srow%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRow()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `pov` to the URL query string
    if (getPov() != null) {
      joiner.add(String.format("%spov%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPov()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `expanded` to the URL query string
    if (getExpanded() != null) {
      joiner.add(String.format("%sexpanded%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getExpanded()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `displayName` to the URL query string
    if (getDisplayName() != null) {
      joiner.add(String.format("%sdisplayName%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDisplayName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `hidden` to the URL query string
    if (getHidden() != null) {
      joiner.add(String.format("%shidden%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getHidden()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

