/*
 * sometitle
 * The REST API for Essbase provides an automation framework for managing Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.appliedolap.essbase.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.appliedolap.essbase.client.model.JAXBElementObject;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.appliedolap.essbase.client.ApiClient;
/**
 * OtlEditMain
 */
@JsonPropertyOrder({
  OtlEditMain.JSON_PROPERTY_EDIT_ACTIONS,
  OtlEditMain.JSON_PROPERTY_OTL_VERSION,
  OtlEditMain.JSON_PROPERTY_VALIDATE,
  OtlEditMain.JSON_PROPERTY_VALIDATE_FORMULAS,
  OtlEditMain.JSON_PROPERTY_KEEP_TRANSACTION,
  OtlEditMain.JSON_PROPERTY_RESTRUCT_OPTION,
  OtlEditMain.JSON_PROPERTY_JSONFORMAT_LOG
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class OtlEditMain {
  public static final String JSON_PROPERTY_EDIT_ACTIONS = "editActions";
  @jakarta.annotation.Nullable
  private List<JAXBElementObject> editActions = new ArrayList<>();

  public static final String JSON_PROPERTY_OTL_VERSION = "otlVersion";
  @jakarta.annotation.Nullable
  private Integer otlVersion;

  public static final String JSON_PROPERTY_VALIDATE = "validate";
  @jakarta.annotation.Nullable
  private Boolean validate;

  public static final String JSON_PROPERTY_VALIDATE_FORMULAS = "validateFormulas";
  @jakarta.annotation.Nullable
  private Boolean validateFormulas;

  public static final String JSON_PROPERTY_KEEP_TRANSACTION = "keepTransaction";
  @jakarta.annotation.Nullable
  private Boolean keepTransaction;

  /**
   * Gets or Sets restructOption
   */
  public enum RestructOptionEnum {
    ALL_DATA(String.valueOf("ALL_DATA")),
    
    NO_DATA(String.valueOf("NO_DATA")),
    
    LOW_DATA(String.valueOf("LOW_DATA")),
    
    IN_DATA(String.valueOf("IN_DATA"));

    private String value;

    RestructOptionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RestructOptionEnum fromValue(String value) {
      for (RestructOptionEnum b : RestructOptionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESTRUCT_OPTION = "restructOption";
  @jakarta.annotation.Nullable
  private RestructOptionEnum restructOption;

  public static final String JSON_PROPERTY_JSONFORMAT_LOG = "jsonformatLog";
  @jakarta.annotation.Nullable
  private Boolean jsonformatLog;

  public OtlEditMain() { 
  }

  public OtlEditMain editActions(@jakarta.annotation.Nullable List<JAXBElementObject> editActions) {
    this.editActions = editActions;
    return this;
  }

  public OtlEditMain addEditActionsItem(JAXBElementObject editActionsItem) {
    if (this.editActions == null) {
      this.editActions = new ArrayList<>();
    }
    this.editActions.add(editActionsItem);
    return this;
  }

  /**
   * Get editActions
   * @return editActions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EDIT_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<JAXBElementObject> getEditActions() {
    return editActions;
  }


  @JsonProperty(JSON_PROPERTY_EDIT_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEditActions(@jakarta.annotation.Nullable List<JAXBElementObject> editActions) {
    this.editActions = editActions;
  }


  public OtlEditMain otlVersion(@jakarta.annotation.Nullable Integer otlVersion) {
    this.otlVersion = otlVersion;
    return this;
  }

  /**
   * Get otlVersion
   * @return otlVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OTL_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getOtlVersion() {
    return otlVersion;
  }


  @JsonProperty(JSON_PROPERTY_OTL_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtlVersion(@jakarta.annotation.Nullable Integer otlVersion) {
    this.otlVersion = otlVersion;
  }


  public OtlEditMain validate(@jakarta.annotation.Nullable Boolean validate) {
    this.validate = validate;
    return this;
  }

  /**
   * Get validate
   * @return validate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALIDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getValidate() {
    return validate;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidate(@jakarta.annotation.Nullable Boolean validate) {
    this.validate = validate;
  }


  public OtlEditMain validateFormulas(@jakarta.annotation.Nullable Boolean validateFormulas) {
    this.validateFormulas = validateFormulas;
    return this;
  }

  /**
   * Get validateFormulas
   * @return validateFormulas
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALIDATE_FORMULAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getValidateFormulas() {
    return validateFormulas;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATE_FORMULAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidateFormulas(@jakarta.annotation.Nullable Boolean validateFormulas) {
    this.validateFormulas = validateFormulas;
  }


  public OtlEditMain keepTransaction(@jakarta.annotation.Nullable Boolean keepTransaction) {
    this.keepTransaction = keepTransaction;
    return this;
  }

  /**
   * Get keepTransaction
   * @return keepTransaction
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEEP_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getKeepTransaction() {
    return keepTransaction;
  }


  @JsonProperty(JSON_PROPERTY_KEEP_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeepTransaction(@jakarta.annotation.Nullable Boolean keepTransaction) {
    this.keepTransaction = keepTransaction;
  }


  public OtlEditMain restructOption(@jakarta.annotation.Nullable RestructOptionEnum restructOption) {
    this.restructOption = restructOption;
    return this;
  }

  /**
   * Get restructOption
   * @return restructOption
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESTRUCT_OPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RestructOptionEnum getRestructOption() {
    return restructOption;
  }


  @JsonProperty(JSON_PROPERTY_RESTRUCT_OPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRestructOption(@jakarta.annotation.Nullable RestructOptionEnum restructOption) {
    this.restructOption = restructOption;
  }


  public OtlEditMain jsonformatLog(@jakarta.annotation.Nullable Boolean jsonformatLog) {
    this.jsonformatLog = jsonformatLog;
    return this;
  }

  /**
   * Get jsonformatLog
   * @return jsonformatLog
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JSONFORMAT_LOG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getJsonformatLog() {
    return jsonformatLog;
  }


  @JsonProperty(JSON_PROPERTY_JSONFORMAT_LOG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJsonformatLog(@jakarta.annotation.Nullable Boolean jsonformatLog) {
    this.jsonformatLog = jsonformatLog;
  }


  /**
   * Return true if this OtlEditMain object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OtlEditMain otlEditMain = (OtlEditMain) o;
    return Objects.equals(this.editActions, otlEditMain.editActions) &&
        Objects.equals(this.otlVersion, otlEditMain.otlVersion) &&
        Objects.equals(this.validate, otlEditMain.validate) &&
        Objects.equals(this.validateFormulas, otlEditMain.validateFormulas) &&
        Objects.equals(this.keepTransaction, otlEditMain.keepTransaction) &&
        Objects.equals(this.restructOption, otlEditMain.restructOption) &&
        Objects.equals(this.jsonformatLog, otlEditMain.jsonformatLog);
  }

  @Override
  public int hashCode() {
    return Objects.hash(editActions, otlVersion, validate, validateFormulas, keepTransaction, restructOption, jsonformatLog);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OtlEditMain {\n");
    sb.append("    editActions: ").append(toIndentedString(editActions)).append("\n");
    sb.append("    otlVersion: ").append(toIndentedString(otlVersion)).append("\n");
    sb.append("    validate: ").append(toIndentedString(validate)).append("\n");
    sb.append("    validateFormulas: ").append(toIndentedString(validateFormulas)).append("\n");
    sb.append("    keepTransaction: ").append(toIndentedString(keepTransaction)).append("\n");
    sb.append("    restructOption: ").append(toIndentedString(restructOption)).append("\n");
    sb.append("    jsonformatLog: ").append(toIndentedString(jsonformatLog)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `editActions` to the URL query string
    if (getEditActions() != null) {
      for (int i = 0; i < getEditActions().size(); i++) {
        if (getEditActions().get(i) != null) {
          joiner.add(getEditActions().get(i).toUrlQueryString(String.format("%seditActions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `otlVersion` to the URL query string
    if (getOtlVersion() != null) {
      joiner.add(String.format("%sotlVersion%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOtlVersion()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `validate` to the URL query string
    if (getValidate() != null) {
      joiner.add(String.format("%svalidate%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getValidate()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `validateFormulas` to the URL query string
    if (getValidateFormulas() != null) {
      joiner.add(String.format("%svalidateFormulas%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getValidateFormulas()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `keepTransaction` to the URL query string
    if (getKeepTransaction() != null) {
      joiner.add(String.format("%skeepTransaction%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getKeepTransaction()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `restructOption` to the URL query string
    if (getRestructOption() != null) {
      joiner.add(String.format("%srestructOption%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRestructOption()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `jsonformatLog` to the URL query string
    if (getJsonformatLog() != null) {
      joiner.add(String.format("%sjsonformatLog%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getJsonformatLog()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

