/*
 * sometitle
 * The REST API for Essbase provides an automation framework for managing Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.appliedolap.essbase.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.appliedolap.essbase.client.ApiClient;
/**
 * QName
 */
@JsonPropertyOrder({
  QName.JSON_PROPERTY_NAMESPACE_U_R_I,
  QName.JSON_PROPERTY_LOCAL_PART,
  QName.JSON_PROPERTY_PREFIX
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class QName {
  public static final String JSON_PROPERTY_NAMESPACE_U_R_I = "namespaceURI";
  @jakarta.annotation.Nullable
  private String namespaceURI;

  public static final String JSON_PROPERTY_LOCAL_PART = "localPart";
  @jakarta.annotation.Nullable
  private String localPart;

  public static final String JSON_PROPERTY_PREFIX = "prefix";
  @jakarta.annotation.Nullable
  private String prefix;

  public QName() { 
  }

  public QName namespaceURI(@jakarta.annotation.Nullable String namespaceURI) {
    this.namespaceURI = namespaceURI;
    return this;
  }

  /**
   * Get namespaceURI
   * @return namespaceURI
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAMESPACE_U_R_I)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNamespaceURI() {
    return namespaceURI;
  }


  @JsonProperty(JSON_PROPERTY_NAMESPACE_U_R_I)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamespaceURI(@jakarta.annotation.Nullable String namespaceURI) {
    this.namespaceURI = namespaceURI;
  }


  public QName localPart(@jakarta.annotation.Nullable String localPart) {
    this.localPart = localPart;
    return this;
  }

  /**
   * Get localPart
   * @return localPart
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCAL_PART)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLocalPart() {
    return localPart;
  }


  @JsonProperty(JSON_PROPERTY_LOCAL_PART)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalPart(@jakarta.annotation.Nullable String localPart) {
    this.localPart = localPart;
  }


  public QName prefix(@jakarta.annotation.Nullable String prefix) {
    this.prefix = prefix;
    return this;
  }

  /**
   * Get prefix
   * @return prefix
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPrefix() {
    return prefix;
  }


  @JsonProperty(JSON_PROPERTY_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrefix(@jakarta.annotation.Nullable String prefix) {
    this.prefix = prefix;
  }


  /**
   * Return true if this QName object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QName qname = (QName) o;
    return Objects.equals(this.namespaceURI, qname.namespaceURI) &&
        Objects.equals(this.localPart, qname.localPart) &&
        Objects.equals(this.prefix, qname.prefix);
  }

  @Override
  public int hashCode() {
    return Objects.hash(namespaceURI, localPart, prefix);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QName {\n");
    sb.append("    namespaceURI: ").append(toIndentedString(namespaceURI)).append("\n");
    sb.append("    localPart: ").append(toIndentedString(localPart)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `namespaceURI` to the URL query string
    if (getNamespaceURI() != null) {
      joiner.add(String.format("%snamespaceURI%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNamespaceURI()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `localPart` to the URL query string
    if (getLocalPart() != null) {
      joiner.add(String.format("%slocalPart%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLocalPart()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `prefix` to the URL query string
    if (getPrefix() != null) {
      joiner.add(String.format("%sprefix%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPrefix()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

