/*
 * sometitle
 * The REST API for Essbase provides an automation framework for managing Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.appliedolap.essbase.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.appliedolap.essbase.client.model.Link;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.appliedolap.essbase.client.ApiClient;
/**
 * ReportBean
 */
@JsonPropertyOrder({
  ReportBean.JSON_PROPERTY_LINKS,
  ReportBean.JSON_PROPERTY_MODIFIED_TIME,
  ReportBean.JSON_PROPERTY_SIZE_IN_BYTES,
  ReportBean.JSON_PROPERTY_LOCKED_BY,
  ReportBean.JSON_PROPERTY_LOCKED,
  ReportBean.JSON_PROPERTY_LOCKED_TIME,
  ReportBean.JSON_PROPERTY_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ReportBean {
  public static final String JSON_PROPERTY_LINKS = "links";
  @jakarta.annotation.Nullable
  private List<Link> links = new ArrayList<>();

  public static final String JSON_PROPERTY_MODIFIED_TIME = "modifiedTime";
  @jakarta.annotation.Nullable
  private Long modifiedTime;

  public static final String JSON_PROPERTY_SIZE_IN_BYTES = "sizeInBytes";
  @jakarta.annotation.Nullable
  private Long sizeInBytes;

  public static final String JSON_PROPERTY_LOCKED_BY = "lockedBy";
  @jakarta.annotation.Nullable
  private String lockedBy;

  public static final String JSON_PROPERTY_LOCKED = "locked";
  @jakarta.annotation.Nullable
  private Boolean locked;

  public static final String JSON_PROPERTY_LOCKED_TIME = "lockedTime";
  @jakarta.annotation.Nullable
  private Long lockedTime;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public ReportBean() { 
  }

  public ReportBean links(@jakarta.annotation.Nullable List<Link> links) {
    this.links = links;
    return this;
  }

  public ReportBean addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Link> getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@jakarta.annotation.Nullable List<Link> links) {
    this.links = links;
  }


  public ReportBean modifiedTime(@jakarta.annotation.Nullable Long modifiedTime) {
    this.modifiedTime = modifiedTime;
    return this;
  }

  /**
   * Get modifiedTime
   * @return modifiedTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getModifiedTime() {
    return modifiedTime;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModifiedTime(@jakarta.annotation.Nullable Long modifiedTime) {
    this.modifiedTime = modifiedTime;
  }


  public ReportBean sizeInBytes(@jakarta.annotation.Nullable Long sizeInBytes) {
    this.sizeInBytes = sizeInBytes;
    return this;
  }

  /**
   * Get sizeInBytes
   * @return sizeInBytes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIZE_IN_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getSizeInBytes() {
    return sizeInBytes;
  }


  @JsonProperty(JSON_PROPERTY_SIZE_IN_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSizeInBytes(@jakarta.annotation.Nullable Long sizeInBytes) {
    this.sizeInBytes = sizeInBytes;
  }


  public ReportBean lockedBy(@jakarta.annotation.Nullable String lockedBy) {
    this.lockedBy = lockedBy;
    return this;
  }

  /**
   * Get lockedBy
   * @return lockedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCKED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLockedBy() {
    return lockedBy;
  }


  @JsonProperty(JSON_PROPERTY_LOCKED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockedBy(@jakarta.annotation.Nullable String lockedBy) {
    this.lockedBy = lockedBy;
  }


  public ReportBean locked(@jakarta.annotation.Nullable Boolean locked) {
    this.locked = locked;
    return this;
  }

  /**
   * Get locked
   * @return locked
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getLocked() {
    return locked;
  }


  @JsonProperty(JSON_PROPERTY_LOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocked(@jakarta.annotation.Nullable Boolean locked) {
    this.locked = locked;
  }


  public ReportBean lockedTime(@jakarta.annotation.Nullable Long lockedTime) {
    this.lockedTime = lockedTime;
    return this;
  }

  /**
   * Get lockedTime
   * @return lockedTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCKED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getLockedTime() {
    return lockedTime;
  }


  @JsonProperty(JSON_PROPERTY_LOCKED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockedTime(@jakarta.annotation.Nullable Long lockedTime) {
    this.lockedTime = lockedTime;
  }


  public ReportBean name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  /**
   * Return true if this ReportBean object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportBean reportBean = (ReportBean) o;
    return Objects.equals(this.links, reportBean.links) &&
        Objects.equals(this.modifiedTime, reportBean.modifiedTime) &&
        Objects.equals(this.sizeInBytes, reportBean.sizeInBytes) &&
        Objects.equals(this.lockedBy, reportBean.lockedBy) &&
        Objects.equals(this.locked, reportBean.locked) &&
        Objects.equals(this.lockedTime, reportBean.lockedTime) &&
        Objects.equals(this.name, reportBean.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, modifiedTime, sizeInBytes, lockedBy, locked, lockedTime, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportBean {\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    modifiedTime: ").append(toIndentedString(modifiedTime)).append("\n");
    sb.append("    sizeInBytes: ").append(toIndentedString(sizeInBytes)).append("\n");
    sb.append("    lockedBy: ").append(toIndentedString(lockedBy)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    lockedTime: ").append(toIndentedString(lockedTime)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `links` to the URL query string
    if (getLinks() != null) {
      for (int i = 0; i < getLinks().size(); i++) {
        if (getLinks().get(i) != null) {
          joiner.add(getLinks().get(i).toUrlQueryString(String.format("%slinks%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `modifiedTime` to the URL query string
    if (getModifiedTime() != null) {
      joiner.add(String.format("%smodifiedTime%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getModifiedTime()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `sizeInBytes` to the URL query string
    if (getSizeInBytes() != null) {
      joiner.add(String.format("%ssizeInBytes%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSizeInBytes()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `lockedBy` to the URL query string
    if (getLockedBy() != null) {
      joiner.add(String.format("%slockedBy%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLockedBy()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `locked` to the URL query string
    if (getLocked() != null) {
      joiner.add(String.format("%slocked%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLocked()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `lockedTime` to the URL query string
    if (getLockedTime() != null) {
      joiner.add(String.format("%slockedTime%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLockedTime()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

