/*
 * sometitle
 * The REST API for Essbase provides an automation framework for managing Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.appliedolap.essbase.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.appliedolap.essbase.client.ApiClient;
/**
 * RTSV
 */
@JsonPropertyOrder({
  RTSV.JSON_PROPERTY_NAME,
  RTSV.JSON_PROPERTY_DESCRIPTION,
  RTSV.JSON_PROPERTY_ALLOW_MISSING,
  RTSV.JSON_PROPERTY_DIMENSION,
  RTSV.JSON_PROPERTY_SINGLE_CHOICE,
  RTSV.JSON_PROPERTY_TYPE,
  RTSV.JSON_PROPERTY_VALUE,
  RTSV.JSON_PROPERTY_LIMIT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RTSV {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_ALLOW_MISSING = "allowMissing";
  @jakarta.annotation.Nullable
  private Boolean allowMissing;

  public static final String JSON_PROPERTY_DIMENSION = "dimension";
  @jakarta.annotation.Nullable
  private String dimension;

  public static final String JSON_PROPERTY_SINGLE_CHOICE = "singleChoice";
  @jakarta.annotation.Nullable
  private Boolean singleChoice;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    STRING(String.valueOf("STRING")),
    
    NUMBER(String.valueOf("NUMBER")),
    
    DATE(String.valueOf("DATE")),
    
    MEMBER(String.valueOf("MEMBER"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  public static final String JSON_PROPERTY_VALUE = "value";
  @jakarta.annotation.Nullable
  private Object value;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @jakarta.annotation.Nullable
  private String limit;

  public RTSV() { 
  }

  public RTSV name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public RTSV description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  public RTSV allowMissing(@jakarta.annotation.Nullable Boolean allowMissing) {
    this.allowMissing = allowMissing;
    return this;
  }

  /**
   * Get allowMissing
   * @return allowMissing
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALLOW_MISSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getAllowMissing() {
    return allowMissing;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_MISSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowMissing(@jakarta.annotation.Nullable Boolean allowMissing) {
    this.allowMissing = allowMissing;
  }


  public RTSV dimension(@jakarta.annotation.Nullable String dimension) {
    this.dimension = dimension;
    return this;
  }

  /**
   * Get dimension
   * @return dimension
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIMENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDimension() {
    return dimension;
  }


  @JsonProperty(JSON_PROPERTY_DIMENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDimension(@jakarta.annotation.Nullable String dimension) {
    this.dimension = dimension;
  }


  public RTSV singleChoice(@jakarta.annotation.Nullable Boolean singleChoice) {
    this.singleChoice = singleChoice;
    return this;
  }

  /**
   * Get singleChoice
   * @return singleChoice
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SINGLE_CHOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSingleChoice() {
    return singleChoice;
  }


  @JsonProperty(JSON_PROPERTY_SINGLE_CHOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSingleChoice(@jakarta.annotation.Nullable Boolean singleChoice) {
    this.singleChoice = singleChoice;
  }


  public RTSV type(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }


  public RTSV value(@jakarta.annotation.Nullable Object value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@jakarta.annotation.Nullable Object value) {
    this.value = value;
  }


  public RTSV limit(@jakarta.annotation.Nullable String limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Get limit
   * @return limit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLimit() {
    return limit;
  }


  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimit(@jakarta.annotation.Nullable String limit) {
    this.limit = limit;
  }


  /**
   * Return true if this RTSV object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RTSV RTSV = (RTSV) o;
    return Objects.equals(this.name, RTSV.name) &&
        Objects.equals(this.description, RTSV.description) &&
        Objects.equals(this.allowMissing, RTSV.allowMissing) &&
        Objects.equals(this.dimension, RTSV.dimension) &&
        Objects.equals(this.singleChoice, RTSV.singleChoice) &&
        Objects.equals(this.type, RTSV.type) &&
        Objects.equals(this.value, RTSV.value) &&
        Objects.equals(this.limit, RTSV.limit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, allowMissing, dimension, singleChoice, type, value, limit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RTSV {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    allowMissing: ").append(toIndentedString(allowMissing)).append("\n");
    sb.append("    dimension: ").append(toIndentedString(dimension)).append("\n");
    sb.append("    singleChoice: ").append(toIndentedString(singleChoice)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDescription()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `allowMissing` to the URL query string
    if (getAllowMissing() != null) {
      joiner.add(String.format("%sallowMissing%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAllowMissing()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `dimension` to the URL query string
    if (getDimension() != null) {
      joiner.add(String.format("%sdimension%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDimension()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `singleChoice` to the URL query string
    if (getSingleChoice() != null) {
      joiner.add(String.format("%ssingleChoice%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSingleChoice()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format("%svalue%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getValue()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `limit` to the URL query string
    if (getLimit() != null) {
      joiner.add(String.format("%slimit%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLimit()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

