name: Publish essbase-rest-client to maven central

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          check-latest: false
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build ${{ github.ref_name }}
        run: |
          mvn -B deploy '-Djava.net.preferIPv4Stack=true' '-Dhttps.protocols=TLSv1.2' '-Dmaven.test.skip=true'
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          SIGN_KEY: ${{ secrets.PRIVATE_SIGNING_KEY }}
          SIGN_KEY_ID: ${{ secrets.PRIVATE_SIGNING_KEY_ID }}
          SIGN_KEY_PASS: ${{ secrets.PRIVATE_SIGNING_KEY_PASSPHRASE }}